
import javax.swing.*;
import java.math.*;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kamva Cewu
 */
public class StockWorth extends javax.swing.JFrame {
       double DebtR,CurrR,PE,GrowthR;
   
    public StockWorth() {
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        txtTotLiabilities = new javax.swing.JTextField();
        txtTotAssets = new javax.swing.JTextField();
        txtSharePrice = new javax.swing.JTextField();
        txtEPS = new javax.swing.JTextField();
        txtCRev = new javax.swing.JTextField();
        txtPRev = new javax.swing.JTextField();
        txtCAssets = new javax.swing.JTextField();
        txtCLiabilities = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDRatio = new javax.swing.JTextField();
        txtPriceEarnings = new javax.swing.JTextField();
        txtCurrentRatio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRevG = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StockWorth");
        setBackground(new java.awt.Color(102, 0, 102));
        setForeground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Total Liabilities:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Share Price:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Earnings Per Share(EPS):");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Total Assets:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Current Revenue:");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("Previous Revenue:");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Current Assets:");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Current Liabilities:");

        btnCalculate.setBackground(new java.awt.Color(0, 0, 0));
        btnCalculate.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.setToolTipText("Compute all the neccesary outputs");
        btnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalculateMouseClicked(evt);
            }
        });
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txtTotLiabilities.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtTotLiabilities.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTotAssets.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtTotAssets.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotAssets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotAssetsActionPerformed(evt);
            }
        });

        txtSharePrice.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtSharePrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtEPS.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtEPS.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCRev.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtCRev.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPRev.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtPRev.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCAssets.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtCAssets.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCLiabilities.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtCLiabilities.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Debt Ratio:");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("P/E Ratio:");

        txtDRatio.setEditable(false);
        txtDRatio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPriceEarnings.setEditable(false);
        txtPriceEarnings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCurrentRatio.setEditable(false);
        txtCurrentRatio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("Current Ratio:");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("Revenue Growth:");

        txtRevG.setEditable(false);
        txtRevG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.setToolTipText("Clears all the fields");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.setToolTipText("Exits/Closes the program");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 0, 51));
        btnLogOut.setText("LOGOUT");
        btnLogOut.setToolTipText("Click this button to logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.setToolTipText("Saves work to file");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSharePrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtTotAssets, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTotLiabilities, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEPS)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDRatio)
                                    .addComponent(txtPriceEarnings))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCRev)
                            .addComponent(txtPRev)
                            .addComponent(txtCAssets)
                            .addComponent(txtCLiabilities)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCurrentRatio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRevG))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnExit)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotLiabilities, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCRev))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEPS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotAssets, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPRev, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSharePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCAssets, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCLiabilities, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDRatio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentRatio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriceEarnings, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRevG, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalculateMouseClicked
       try{
       double TotLiab,SP, TotAss,EPS, CurrentR, PrevR,CurrAss, CurrLiab ; //Variable declaration
       //The following code extracts the data from the input fields and converts it into the neccesary format for manipulation.
       TotLiab=Float.parseFloat(this.txtTotLiabilities.getText());
       TotAss=Float.parseFloat(this.txtTotAssets.getText());
       SP=Float.parseFloat(this.txtSharePrice.getText());
       EPS=Float.parseFloat(this.txtEPS.getText());
       CurrAss=Float.parseFloat(this.txtCAssets.getText());
       CurrLiab=Float.parseFloat(this.txtCLiabilities.getText());
       CurrentR=Float.parseFloat(this.txtCRev.getText());
       PrevR=Float.parseFloat(this.txtPRev.getText());
       DebtR=TotLiab/TotAss;
       DebtR=Math.round(DebtR*100.0)/100.0; //This is where we round the value off
       CurrR=CurrAss/CurrLiab;
       CurrR=Math.round(CurrR*100.0)/100.0; //This is where we round the value off
       PE=SP/EPS;
       PE=Math.round(PE*100.0)/100.0; //This is where we round the value off
       GrowthR=(CurrentR-PrevR)/PrevR*100;
       GrowthR=Math.round(GrowthR*100.0)/100.0; //This is where we round the value off
       if(DebtR>=0.5){
           this.txtDRatio.setText(" "+DebtR+" ,Bad");
       }if (DebtR<0.5){
           this.txtDRatio.setText(" "+DebtR+" ,Good");
       }if (CurrR>=1 && CurrR<=5){
            this.txtCurrentRatio.setText(" "+CurrR+" ,Good");
       }if (CurrR>5){
           this.txtCurrentRatio.setText(" "+CurrR+" ,Great");
       }if (CurrR<1){
           this.txtCurrentRatio.setText(" "+CurrR+" ,Bad");
       }if (PE<=10){
           this.txtPriceEarnings.setText(" "+PE+" ,Underpriced");
       }if (PE>10 && PE<20){
           this.txtPriceEarnings.setText(" "+PE+" ,Fairly Priced");
       }if (PE>=20){
           this.txtPriceEarnings.setText(" "+PE+" ,Overpriced");
       }if (GrowthR>=3){
           this.txtRevG.setText(" "+GrowthR+" ,Good");
       }if (GrowthR<=1){
           this.txtRevG.setText(" "+GrowthR+" ,Bad");
       }
       
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null,"Check input for validity","Error",JOptionPane.ERROR_MESSAGE);
           this.txtCAssets.setText("");
           this.txtCLiabilities.setText("");
           this.txtCRev.setText("");
           this.txtDRatio.setText("");
           this.txtCurrentRatio.setText("");
           this.txtEPS.setText("");
           this.txtPRev.setText("");
           this.txtPriceEarnings.setText("");
           this.txtRevG.setText("");
           this.txtSharePrice.setText("");
           this.txtTotAssets.setText("");
           this.txtTotLiabilities.setText("");
       }
    }//GEN-LAST:event_btnCalculateMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
       this.txtCAssets.setText("");
       this.txtCLiabilities.setText("");
       this.txtCRev.setText("");
       this.txtCurrentRatio.setText("");
       this.txtDRatio.setText("");
       this.txtEPS.setText("");
       this.txtPRev.setText("");
       this.txtPriceEarnings.setText("");
       this.txtRevG.setText("");
       this.txtSharePrice.setText("");
       this.txtTotAssets.setText("");
       this.txtTotLiabilities.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
      //This button closs the program.
       int Confirm=JOptionPane.showConfirmDialog(null,"Are you sure you wish to exit?");
       if (Confirm==0){
           System.exit(0);
       }
    }//GEN-LAST:event_btnExitMouseClicked

    private void txtTotAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotAssetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotAssetsActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
       //This button closes the current page and takes the user to the login page. 
       LoginPage formLogin=new LoginPage();
       this.setVisible(false);
       formLogin.setVisible(true);
       formLogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFrame parentFrame=new JFrame();          //This opens a file chooser for the user
        JFileChooser fileChooser= new JFileChooser();    //Creates an object named fileChooser
        fileChooser.setDialogTitle("Choose where to save file");   //Title of the file chooser
        int response=fileChooser.showSaveDialog(parentFrame);    //Takes response from user(Save or Cancel)
        if(response==JFileChooser.APPROVE_OPTION){              //If the user clicks 'Save'
        File fileToSave= new File(fileChooser.getSelectedFile()+".doc");    //Adds a .doc to file name to create word document
        try{
        PrintWriter SaveStock= new PrintWriter(fileToSave);     //Creates a file in the directory 'fileToSave' to store following details
        SaveStock.println("The Debt ratio is "+DebtR);
        SaveStock.println("The P/E ratio is "+PE);
        SaveStock.println("The Current ratio is "+CurrR);
        SaveStock.println("The Revenue growth ratio is "+GrowthR);
        JOptionPane.showMessageDialog(null,"Information successfully saved to file","Saved Successfully",JOptionPane.INFORMATION_MESSAGE);
        SaveStock.close();                                      //Closes the connection to the file to avoid memory leak
        }catch(FileNotFoundException e){
             JOptionPane.showMessageDialog(null,"Could not save to file");
        }
        }
        if(response==JFileChooser.ABORT || response==JFileChooser.CANCEL_OPTION){   //If user clicks 'Cancel'
             JOptionPane.showMessageDialog(null,"Operation cancelled","Save Unsuccessfull",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockWorth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockWorth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockWorth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockWorth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockWorth().setVisible(true);
                LoginPage form1=new LoginPage();
                form1.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSave;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCAssets;
    private javax.swing.JTextField txtCLiabilities;
    private javax.swing.JTextField txtCRev;
    private javax.swing.JTextField txtCurrentRatio;
    private javax.swing.JTextField txtDRatio;
    private javax.swing.JTextField txtEPS;
    private javax.swing.JTextField txtPRev;
    private javax.swing.JTextField txtPriceEarnings;
    private javax.swing.JTextField txtRevG;
    private javax.swing.JTextField txtSharePrice;
    private javax.swing.JTextField txtTotAssets;
    private javax.swing.JTextField txtTotLiabilities;
    // End of variables declaration//GEN-END:variables
}
